version: 0.2

env:
  variables:
    IMAGE_NAME: simple-python-flask-app
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub"
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

  build:
    commands:
      - echo "Building Docker image"
      - docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Pushing image to Docker Hub"
      - docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG
      - echo "Build completed successfully"
